#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Other cookbooks
# https://github.com/joevandyk/chef-cookbooks
# https://github.com/37signals/37s_cookbooks
# https://github.com/cookbooks
# https://github.com/engineyard/ey-cloud-recipes

cookbook "apt"
cookbook "build-essential"
cookbook "database"
cookbook "git"
# cookbook "mysql"
cookbook "squid"
cookbook "apt"

cookbook "application", github: 'poise/application'
cookbook "application_ruby", github: 'better-cooking/application_ruby'
cookbook "nginx", github: 'better-cooking/nginx'

cookbook 'swap', github: 'sethvargo-cookbooks/swap', ref: 'v0.3.6'
cookbook 'rbenv', github: 'fnichol/chef-rbenv', ref: 'v0.7.2'
cookbook 'ruby_build', github: 'fnichol/chef-ruby_build', ref: 'v0.8.0'

cookbook 'hetzner_one', path: 'site-cookbooks/hetzner_one'
cookbook 'badgeworld', path: 'site-cookbooks/badgeworld'
