#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Other cookbooks
# https://github.com/joevandyk/chef-cookbooks
# https://github.com/37signals/37s_cookbooks
# https://github.com/cookbooks
# https://github.com/engineyard/ey-cloud-recipes

cookbook "database"
# cookbook "mysql"
cookbook "application_ruby"
cookbook 'ruby_from_source', :git => 'git://github.com/better-cooking/ruby_from_source.git'
cookbook 'source_package', :git => 'git://github.com/averell23/source_package.git'
cookbook "rails_install", :git => "git://github.com/averell23/rails_install.git"